#!/usr/bin/env bash
# Buyer-facing one-shot quickstart: kind cluster -> helm install -> first key.
#
# Pairs with docs/operations/quickstart.md. Prereqs: docker, kind, helm,
# kubectl, uv, and ANTHROPIC_API_KEY in env (or in .env in repo root).
#
# What this does (idempotent — safe to re-run):
#   1. Creates a kind cluster `metis-trial` if it doesn't exist.
#   2. Builds the gateway image and loads it into the cluster.
#   3. Issues a gateway key out-of-band, wraps it in a Secret.
#   4. helm install / upgrade against infra/gateway/helm/.
#   5. Waits for the deployment to come Ready.
#   6. Starts a port-forward in the background and writes a .quickstart-state
#      file with the key + port + cluster name so tear-down.sh can clean up.
#
# Tear-down with:
#   infra/gateway/scripts/tear-down.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$REPO_ROOT"

CLUSTER_NAME="${METIS_TRIAL_CLUSTER:-metis-trial}"
NAMESPACE="${METIS_TRIAL_NAMESPACE:-metis-gateway}"
RELEASE="${METIS_TRIAL_RELEASE:-metis-gateway}"
PORT="${METIS_TRIAL_PORT:-18422}"
STATE_DIR="${METIS_TRIAL_STATE_DIR:-$REPO_ROOT/.metis-trial}"
STATE_FILE="$STATE_DIR/state.env"
KEYS_FILE="$STATE_DIR/keys.json"
ISSUE_OUT="$STATE_DIR/issue.out"

mkdir -p "$STATE_DIR"

# Source .env if present, but do NOT clobber values already in the env.
if [[ -f "$REPO_ROOT/.env" && -z "${ANTHROPIC_API_KEY:-}" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
fi

if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
  echo "ANTHROPIC_API_KEY not set (env or .env in repo root). Aborting." >&2
  exit 2
fi

for cmd in docker kind helm kubectl uv; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "missing required command: $cmd" >&2
    exit 2
  fi
done

echo "==> Ensuring kind cluster '$CLUSTER_NAME' exists"
if ! kind get clusters 2>/dev/null | grep -qx "$CLUSTER_NAME"; then
  kind create cluster --name "$CLUSTER_NAME" --wait 2m
else
  echo "    cluster '$CLUSTER_NAME' already exists"
fi

echo "==> Building metis-gateway:trial image"
docker build --quiet -t metis-gateway:trial -f infra/gateway/Dockerfile . >/dev/null

echo "==> Loading image into kind cluster"
kind load docker-image metis-gateway:trial --name "$CLUSTER_NAME"

echo "==> Ensuring namespace '$NAMESPACE'"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null

echo "==> Issuing gateway key (out-of-band; chart can't seed an empty keystore)"
if [[ ! -f "$KEYS_FILE" ]]; then
  uv run metis gateway issue-key \
      --keystore "$KEYS_FILE" \
      --name "trial-client" \
      --workspace "$REPO_ROOT" > "$ISSUE_OUT"
else
  echo "    reusing existing key in $KEYS_FILE"
fi
TOKEN="$(awk '/^token:/ {print $2}' "$ISSUE_OUT")"
if [[ -z "$TOKEN" ]]; then
  echo "could not parse token from $ISSUE_OUT (re-issuing)" >&2
  rm -f "$KEYS_FILE"
  uv run metis gateway issue-key \
      --keystore "$KEYS_FILE" \
      --name "trial-client" \
      --workspace "$REPO_ROOT" > "$ISSUE_OUT"
  TOKEN="$(awk '/^token:/ {print $2}' "$ISSUE_OUT")"
fi

echo "==> Wrapping keystore in a Secret"
kubectl -n "$NAMESPACE" create secret generic metis-gateway-keystore \
    --from-file=keys.json="$KEYS_FILE" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null

echo "==> helm upgrade --install $RELEASE"
helm upgrade --install "$RELEASE" "$REPO_ROOT/infra/gateway/helm/" \
    --namespace "$NAMESPACE" \
    --set image.repository=metis-gateway \
    --set image.tag=trial \
    --set image.pullPolicy=Never \
    --set provider.anthropicApiKey="$ANTHROPIC_API_KEY" \
    --set keystore.existingSecret=metis-gateway-keystore \
    --wait --timeout 3m >/dev/null

echo "==> Waiting for deployment to come Ready"
kubectl -n "$NAMESPACE" rollout status deploy/"$RELEASE" --timeout=120s

echo "==> Stopping any prior port-forward on port $PORT"
if [[ -f "$STATE_DIR/port-forward.pid" ]]; then
  kill "$(cat "$STATE_DIR/port-forward.pid")" 2>/dev/null || true
  rm -f "$STATE_DIR/port-forward.pid"
fi

echo "==> Starting port-forward 127.0.0.1:$PORT -> svc/$RELEASE:8422"
nohup kubectl -n "$NAMESPACE" port-forward svc/"$RELEASE" "$PORT:8422" \
    >"$STATE_DIR/port-forward.log" 2>&1 &
echo "$!" > "$STATE_DIR/port-forward.pid"
# Wait up to 5s for the forward to come up.
for _ in 1 2 3 4 5; do
  if curl --silent --fail "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

cat > "$STATE_FILE" <<EOF
# Generated by infra/gateway/scripts/quickstart.sh — do not edit by hand.
METIS_TRIAL_CLUSTER="$CLUSTER_NAME"
METIS_TRIAL_NAMESPACE="$NAMESPACE"
METIS_TRIAL_RELEASE="$RELEASE"
METIS_TRIAL_PORT="$PORT"
METIS_TRIAL_GATEWAY_URL="http://127.0.0.1:$PORT"
METIS_TRIAL_GATEWAY_KEY="$TOKEN"
EOF

echo
echo "==> Trial gateway ready"
echo "    gateway URL:  http://127.0.0.1:$PORT"
echo "    gateway key:  $TOKEN"
echo "    healthz:      curl http://127.0.0.1:$PORT/healthz"
echo
echo "Next: run the pre-baked workload through the gateway."
echo "  uv run metis trial --gateway-url http://127.0.0.1:$PORT --gateway-key $TOKEN"
echo
echo "State written to $STATE_FILE. Tear down with:"
echo "  infra/gateway/scripts/tear-down.sh"
